### ISSUE TITLE
大佬，那个用户个人界面能否直接在评论后面显示那条评论所在官号吗

### ISSUE THREAD

**Issue by Lyin-nil** [wjrtxz02539/Mzr#2]
就是这里（对不起，不怎么会用，不知道图片能显示吗）
![image](https://user-images.githubusercontent.com/106391522/173248845-88655b1f-7bb0-459c-b7ff-5c36266b0de9.png)
以及能否添加一个人的评论在各个官号下占比的饼状图
感谢大佬了

**Comment by wjrtxz02539** [comment]
已更新
